# Generated by Django 5.1.1 on 2024-10-09 17:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_restaurantbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantbanner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='restaurantbanner',
            name='title',
        ),
        migrations.AddField(
            model_name='restaurantbanner',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
